//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevHacksService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clusters
    {
        public Clusters()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int RestaurantID { get; set; }
        public long Time { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
