//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevHacksService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foods
    {
        public Foods()
        {
            this.Suborders = new HashSet<Suborders>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int RestaurantID { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string Image { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
        public virtual ICollection<Suborders> Suborders { get; set; }
    }
}
