//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevHacksService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AspNetRoles> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public DbSet<AspNetUsers> AspNetUsers { get; set; }
        public DbSet<Clusters> Clusters { get; set; }
        public DbSet<Foods> Foods { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Restaurants> Restaurants { get; set; }
        public DbSet<Suborders> Suborders { get; set; }
        public DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<GetClustersInArea_Result> GetClustersInArea(Nullable<double> latitude, Nullable<double> longitude, Nullable<double> radius)
        {
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(double));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("radius", radius) :
                new ObjectParameter("radius", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClustersInArea_Result>("GetClustersInArea", latitudeParameter, longitudeParameter, radiusParameter);
        }
    
        public virtual ObjectResult<GetClustersInAreaEntity_Result> GetClustersInAreaEntity(Nullable<double> latitude, Nullable<double> longitude, Nullable<double> radius)
        {
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(double));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("radius", radius) :
                new ObjectParameter("radius", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClustersInAreaEntity_Result>("GetClustersInAreaEntity", latitudeParameter, longitudeParameter, radiusParameter);
        }
    
        public virtual ObjectResult<GetOrdersInArea_Result> GetOrdersInArea(Nullable<double> latitude, Nullable<double> longitude, Nullable<double> radius)
        {
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(double));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("radius", radius) :
                new ObjectParameter("radius", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrdersInArea_Result>("GetOrdersInArea", latitudeParameter, longitudeParameter, radiusParameter);
        }
    
        public virtual ObjectResult<GetOrdersInAreaEntity_Result> GetOrdersInAreaEntity(Nullable<double> latitude, Nullable<double> longitude, Nullable<double> radius)
        {
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(double));
    
            var radiusParameter = radius.HasValue ?
                new ObjectParameter("radius", radius) :
                new ObjectParameter("radius", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrdersInAreaEntity_Result>("GetOrdersInAreaEntity", latitudeParameter, longitudeParameter, radiusParameter);
        }
    }
}
