//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevHacksService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Suborders = new HashSet<Suborders>();
        }
    
        public int Id { get; set; }
        public int RestaurantID { get; set; }
        public double Price { get; set; }
        public int Discount { get; set; }
        public long Time { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int UserID { get; set; }
        public int Done { get; set; }
        public Nullable<int> ClusterID { get; set; }
    
        public virtual Clusters Clusters { get; set; }
        public virtual Restaurants Restaurants { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Suborders> Suborders { get; set; }
    }
}
