//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevHacksService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurants
    {
        public Restaurants()
        {
            this.Clusters = new HashSet<Clusters>();
            this.Foods = new HashSet<Foods>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Specific { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Clusters> Clusters { get; set; }
        public virtual ICollection<Foods> Foods { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
